document.writeln("<section id=\'footer\'>");
document.writeln("		  <div id=\'footer-info\' class=\'layui-main\'>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>首页</h2>");
document.writeln("					<a href="+fRoot+"templetes/result-list.html\>环保科技成果</a>");
document.writeln("					<a href="+fRoot+"templetes/demand-list.html\>环保科技需求</a>");
document.writeln("					<a href="+fRoot+"templetes/expert-list.html\>专家库</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>信息平台</h2>");
document.writeln("					<a href="+fRoot+"templetes/register.html\>用户注册</a>");
document.writeln("					<a href="+fRoot+"templetes/add-demand.html\>需求发布</a>");
document.writeln("					<a href="+fRoot+"empletes/add-result.html\>成果发表</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>专家库</h2>");
document.writeln("					<a href="+fRoot+">申报专家</a>");
document.writeln("					<a href="+fRoot+"templetes/expert-list.html\>专家信息</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>行业资讯</h2>");
document.writeln("					<a href="+fRoot+"templetes/article-list.html?type=1\>转化流程</a>");
document.writeln("					<a href="+fRoot+"templetes/article-list.html?type=2\>金融服务</a>");
document.writeln("					<a href="+fRoot+"templetes/article-list.html?type=3\>潜力评估</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<a class=\'nav-item footer-qrpic\'>");
document.writeln("					<img src="+fRoot+"images/footericon/qr.png\ />");
document.writeln("				</a>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<a class=\'nav-item footer-qrpic\'>");
document.writeln("					<img src="+fRoot+"images/footericon/qr.png\ />");
document.writeln("				</a>");
document.writeln("			</ul>");
document.writeln("		  </div>");
document.writeln("		  <div class=\'layui-main\' id=\'footer-flink-content\'>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'\'><img src="+fRoot+"images/footericon/logo1.png\ /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'\'><img src="+fRoot+"images/footericon/logo2.png\ /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'\'><img src="+fRoot+"images/footericon/logo3.png\ /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'\'><img src="+fRoot+"images/footericon/logo4.png\ /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'\'><img src="+fRoot+"images/footericon/logo5.png\ /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'\'><img src="+fRoot+"images/footericon/logo6.png\ /></a>");
document.writeln("		  </div>");
document.writeln("		  <div id=\'footer-content\'>");
document.writeln("			<p>© 2018 <a href="+fRoot+">环保科技成果.com</a> 展示平台</p>");
document.writeln("			<p>*推荐使用Chrome/Firefox内核浏览器访问本站</p>");
document.writeln("			");
document.writeln("		  </div>");
document.writeln("		</section>");