document.writeln("<section id=\'nav-bar\' class=\'layui-header header header-doc\'>");
document.writeln("      <div class=\'layui-main\'>");
document.writeln("        <a class=\'logo\' href="+fRoot+"index.html>");
document.writeln("          <img src="+fRoot+"images/globe/logo_head.png\ />");
document.writeln("        </a>");
document.writeln("        <ul class=\'layui-nav\' id=\'navlist-right\' lay-filter=\'\'>");
document.writeln("          <li class=\'layui-nav-item\'><a href="+fRoot+"index.html>首页</a></li>");
document.writeln("          <li class=\'layui-nav-item\'><a href="+fRoot+"templetes/result-list.html\>成果</a></li>");
document.writeln("          <li class=\'layui-nav-item\'><a href="+fRoot+"templetes/demand-list.html\>需求</a></li>");
document.writeln("          <li class=\'layui-nav-item\'><a href="+fRoot+"templetes/expert-list.html\>专家库</a></li>");
document.writeln("          <li class=\'layui-nav-item\'>");
document.writeln("          <a href="+fRoot+"templetes/article-list.html\>行业资讯</a>");
document.writeln("          <dl class=\'layui-nav-child\'> <!-- 二级菜单 -->");
document.writeln("            <dd><a href="+fRoot+"templetes/article-list.html?type=1\>转化流程</a></dd>");
document.writeln("            <dd><a href="+fRoot+"templetes/article-list.html?type=2\>金融服务</a></dd>");
document.writeln("            <dd><a href="+fRoot+"templetes/article-list.html?type=3\>潜力评估</a></dd>");
document.writeln("          </dl>");
document.writeln("          </li>");
document.writeln("          <li id=\'userLogin\' class=\'layui-nav-item\'><a>注册/登陆</a></li>");
document.writeln("          <li id=\'userCenter\' class=\'layui-nav-item\'>");
document.writeln("              <a href=\'javascript:;\'>");
document.writeln("                <img class=\'layui-nav-img\' src="+fRoot+"images/globe/defaultHeadPic.jpg\>");
document.writeln("              </a>");
document.writeln("              <dl class=\'layui-nav-child\'>");
document.writeln("                <dd><a href="+fRoot+"templetes/userPanel.html#utab=cgInfo>基本资料</a></dd>");
document.writeln("                <dd><a href="+fRoot+"templetes/userPanel.html#utab=cgPwd>安全设置</a></dd>");
document.writeln("                <dd><a id=\'logOutBtn\' href="+fRoot+"'>注销</a></dd>");
document.writeln("              </dl>");
document.writeln("              </li>       ");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </section> ");