document.writeln("<section id=\'footer\'>");
document.writeln("		  <div id=\'footer-info\' class=\'layui-main\'>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>首页</h2>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/templetes/result-list.html\'>环保科技成果</a>");
document.writeln("					<a href=\'/templetes/demand-list.html\'>环保科技需求</a>");
document.writeln("					<a href=\'/templetes/expert-list.html\'>专家库</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>信息平台</h2>");
document.writeln("					<a href=\'/templetes/register.html\'>用户注册</a>");
document.writeln("					<a href=\'/templetes/add-demand.html\'>需求发布</a>");
document.writeln("					<a href=\'/templetes/add-result.html\'>成果发表</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>专家库</h2>");
document.writeln("					<a href=\'/\'>申报专家</a>");
document.writeln("					<a href=\'/templetes/expert-list.html\'>专家信息</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>行业资讯</h2>");
document.writeln("					<a href=\'/templetes/article-list.html?type=1\'>转化流程</a>");
document.writeln("					<a href=\'/templetes/article-list.html?type=1\'>金融服务</a>");
document.writeln("					<a href=\'/templetes/article-list.html?type=1\'>潜力评估</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<a class=\'nav-item footer-qrpic\'>");
document.writeln("					<img src=\'/images/footericon/qr.png\' />");
document.writeln("				</a>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\'>");
document.writeln("				<a class=\'nav-item footer-qrpic\'>");
document.writeln("					<img src=\'/images/footericon/qr.png\' />");
document.writeln("				</a>");
document.writeln("			</ul>");
document.writeln("		  </div>");
document.writeln("		  <div class=\'layui-main\' id=\'footer-flink-content\'>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/wxlogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/aqlogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/bcplogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/360logo.gif\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/cxlogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/rzlogo.png\' /></a>");
document.writeln("		  </div>");
document.writeln("		  <div id=\'footer-content\'>");
document.writeln("			<p>© 2017 <a href=\'/\'>环保科技成果.com</a> 展示平台</p>");
document.writeln("			<p>*推荐使用Chrome/Firefox内核浏览器访问本站</p>");
document.writeln("			");
document.writeln("		  </div>");
document.writeln("		</section>");