document.writeln("<section id=\'footer\'>");
document.writeln("		  <div id=\'footer-info\' class=\'layui-main\'>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>首页</h2>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>首页</h2>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>首页</h2>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<li class=\'nav-item\'>");
document.writeln("					<h2>首页</h2>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("					<a href=\'/\'>首页信息</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<a class=\'nav-item footer-qrpic\'>");
document.writeln("					<img src=\'/images/footericon/qr.png\' />");
document.writeln("				</a>");
document.writeln("			</ul>");
document.writeln("			<ul class=\'footer-icon layui-col-sm2\' href=\'/\'>");
document.writeln("				<a class=\'nav-item footer-qrpic\'>");
document.writeln("					<img src=\'/images/footericon/qr.png\' />");
document.writeln("				</a>");
document.writeln("			</ul>");
document.writeln("		  </div>");
document.writeln("		  <div class=\'layui-main\' id=\'footer-flink-content\'>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/wxlogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/aqlogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/bcplogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/360logo.gif\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/cxlogo.png\' /></a>");
document.writeln("			<a class=\'footer-icon layui-col-sm2\' href=\'/\'><img src=\'/images/footericon/rzlogo.png\' /></a>");
document.writeln("		  </div>");
document.writeln("		  <div id=\'footer-content\'>");
document.writeln("			<p>© 2017 <a href=\'/\'>环保科技成果.com</a> 展示平台</p>");
document.writeln("			<p>*推荐使用Chrome/Firefox内核浏览器访问本站</p>");
document.writeln("			");
document.writeln("		  </div>");
document.writeln("		</section>");